### ISSUE TITLE
Segmentation fault: 11 

### ISSUE THREAD

**Issue by ttorbik** [yoshimkd/swift-code-types-navigator#3]
Not sure what I am doing wrong here but I keep receiving a Segmentation fault: 11 error

![screen shot 2018-11-30 at 4 14 02 pm](https://user-images.githubusercontent.com/21199261/49317730-3c263a00-f4bb-11e8-8e96-884b23c468bc.png)

**Comment by yoshimkd** [comment]
Hello @ttorbik ,

Thanks for reporting this, I reproduced it and fixed the issue by updating the version of the swift-ast dependency. Pull the latest version and the issue should be resolved. I'm closing this issue, feel free to report again if there are any problems.

Best Regards,
Jovan
